### ISSUE TITLE
Modify the submission template to ask a question about upstreaming the code

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/software-peer-review#40]
In our meeting we discussed that it'd be good to ask authors if they've considered upstreaming an improvement to other related packages as opposed to releasing a new package. We could add a question to the template like:

* Are there related projects to this submission that would benefit from upstreaming this functionality? If so, what is your reasoning for releasing a new project?

**Comment by lwasser** [comment]
Such a great suggestion @choldgraf !! i wonder if we can make the language a bit more friendly for those who might not know what upstreaming means? 

maybe something like

* Are there related and already developed projects that might benefit from adding this functionality back to their project rather than creating a new package? If so...

Or something like that??

**Comment by choldgraf** [comment]
I think that's much better wording!

**Comment by cmarmo** [comment]
The [current template](https://github.com/pyOpenSci/software-submission/blob/2d1a110ac8eec77493e52121cf6fcf7a64bc2b6c/.github/ISSUE_TEMPLATE/submit-software-for-review.md?plain=1#L72) asks:
```
Are there other Python packages that accomplish the same thing? If so, how does yours differ?
```
Is that sufficient? I can offer a PR otherwise, implementing the suggested phrasing.

**Comment by lwasser** [comment]
@cmarmo you are correct. we did add this so i'll close this issue! many thanks!!
