### ISSUE TITLE
repostatus badge

### ISSUE THREAD

**Issue by megies** [pyOpenSci/software-peer-review#41]
Having that repostatus badge is prominently advertized in the packaging guidelines that I got pointed at during the submission of package review "new issue" process. (pyOpenSci/software-review/issues/16)

I didn't know it but from looking at the docs (their extra light gray text on white background is insanely hard to read) and if I'm not missing anything here (mostly due to skipping the longish text bits due to said tough readability), it seems to be static and not dynamically determined from any introspection on the target repo? If that is accurate, the point of that badge evades me. You can add an "active" badge to a repo and then bury it six feet under the next day and 20 years later people will be staring at an "active" badge in the README of a Python 3 project when Python 5 went EOL two weeks ago? :stuck_out_tongue_winking_eye:

**Comment by lwasser** [comment]
hi @megies !! 👋 Thank you for the package submission AND for the issue here!! can you kindly help me understand: 

1. what text is hard to read? that is something we can fix but i'm a bit unclear about what page you are looking at. A link and quick screenshot would be super helpful!!
2. and then what badge are you u referring to? We have a pyopensci reviewed badge that we ask you uto add to your readme after the review. a few screenshots would help me better understand and then address the issues!

we have so much content in our dev_guide and it's definitely a work in progress. i'm looking forward to addressing some of the bugs that you have found!! 
 
thank you again! we will have a look at your submission soon (maybe after i get back from agu however given how busy this conference has been :)

**Comment by megies** [comment]
### 1.

 It's mentioned [here](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html#README) and I ended up on that page during filing that "new review" issue. You end up on that page following a link in the "new review issue" template:

![Screenshot from 2019-12-11 22-41-12](https://user-images.githubusercontent.com/1842780/70688791-d9ad6f80-1cb2-11ea-8de5-f292d92624a0.png)

---


```
## Technical checks

For details about the pyOpenSci packaging requirements, see our [packaging guide](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html). Confirm each of the following by checking the box.  This package:
```

---

### 2. 

The below badge is prominently advertized kind of as a requirement almost, but with it's static nature (e.g. hardcoded `"active"` status) its usefulness evades me ;)


---

![Screenshot from 2019-12-11 22-42-29](https://user-images.githubusercontent.com/1842780/70688869-019cd300-1cb3-11ea-9cd0-688d26cfacae.png)

---




> thank you again! we will have a look at your submission soon (maybe after i get back from agu however given how busy this conference has been :)

No worries, no hurry at all. Just wanted to do it right away, lest I forget. You folks are definitely working on something that is needed and would be a very useful guidance for the hero code zoo out there, so.. happy to advertize your efforts.

**Comment by lwasser** [comment]
hi @megies my gosh this is a very old issue as well :)  i am going to close this issue as we don't require / talk about that badge right now. we do intend to create a page on badges in our newer package guide! but that will be a WIP in the future. 

i hope you are well!!

**Comment by lwasser** [comment]
@all-contributors please add @megies for code, review
